# Generated by Django 5.2 on 2025-05-17 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tamanho', models.CharField(blank=True, default='', max_length=50)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('ultima_compra', models.DateField(blank=True, null=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='estoque.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('produto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estoque.produto')),
                ('dosagem', models.CharField(max_length=50)),
            ],
            bases=('estoque.produto',),
        ),
    ]
