services:
  - type: web
    name: farmcontrol
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn farmcontrol.wsgi
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: farmcontrol-db
          property: connectionString

databases:
  - name: farmcontrol-db
    plan: free


